brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
    path(
        "<int:pk>/edit/", TodoListUpdateView.as_view(), name="todo_list_update"
    ),
    path(
        "<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/",
        TodoItemCreateView.as_view(),
        name="todo_item_create",
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy

from todos.models import TodoList, TodoItem

# Create your views here.


class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"
    context_object_name = "todolist"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todo_items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todo_items/update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>👌</title>
</head>
    <nav>
        <p>
            <a href="{% url 'todo_list_list' %}">Home</a>
        </p>
            <a href="{% url 'todo_list_create' %}">Create a new list</a>
        </p>
        <p>
            <a href="{% url 'todo_item_create' %}">Create a new item</a>
        </p>
    </nav>
<body>
    {% block main %}
    {% endblock main %}
</body>

</html>

todos/templates/todo_items/create.html
{% extends 'base.html' %}

{% block main %}
<main>
    <div>
        <h1>Create a new item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock main %}

todos/templates/todo_items/update.html
{% extends 'base.html' %}

{% block main %}
<main>
    <div>
        <h1>Update item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
</main>
{% endblock main %}

todos/templates/todos/create.html
{% extends 'base.html' %}

{% block main %}
<main>
  <div>
    <h1>Create a new list</h1>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock main %}

todos/templates/todos/delete.html
{% extends 'base.html' %}

{% block main %}
<main>
    <div>
      <h1>Are you sure?</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Delete</button>
      </form>
    </div>
  </main>
{% endblock main %}

todos/templates/todos/detail.html
{% extends 'base.html' %}

{% block main %}
<main>
    <div>
        <h1>
            <td> {{ todolist }} </td>
        </h1>
        <p>
            <a href="{% url 'todo_list_update' todolist.id %}">Edit</a>
        </p>
        <p>
            <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
        </p>
        <h2>Task</h2>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for task in todolist.items.all  %}
                <tr>
                    <td> 
                        <a href="{% url 'todo_item_update' task.pk %}">{{ task }}</a>
                    </td>
                    <td> {{ task.due_date|date:"M d, Y" }} </td>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock main %}

todos/templates/todos/list.html
{% extends 'base.html' %}

{% block main %}
<main>
    <div>
        <h1> My lists</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                {% for list in todolist_list.all %}
                <td>
                    <a href="{% url 'todo_list_detail' list.pk %}" >{{ list.name }} </a></td>
                <td>
                     {{ list.items.all | length }}
                </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock main %}

todos/templates/todos/update.html
{% extends 'base.html' %}

{% block main %}
<main>
    <div>
        <h1> Updated list </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
</main>
{% endblock main %}